connection=JMS
temn.tti.jms.config.file.name=activemq.xml
temn.tti.jms.security.password=admin

temn.tti.queue.b2f.request.queue=t24IFInboundQueue
temn.tti.queue.b2f.request.queue.bo=t24IFInboundQueue_BO
temn.tti.queue.b2f.input.queue=T24_JMS
temn.tti.queue.b2f.input.queue.bo=T24_JMS_BO
temn.tti.queue.b2f.single.input.queue=T24_IN
temn.tti.queue.b2f.single.input.queue.bo=T24_IN_BO
temn.tti.queue.b2f.batch.input.queue=T24_BATCH_IN
temn.tti.queue.b2f.batch.input.queue.bo=T24_BATCH_IN_BO
temn.tti.queue.b2f.output.queue=XML_B2F
temn.tti.queue.b2f.output.queue.bo=XML_B2F_BO
temn.tti.queue.f2b.tap.input.queue=XML_F2B
temn.tti.queue.f2b.tap.input.queue.bo=XML_F2B_BO
temn.tti.queue.f2b.tap.slow.queue=SLOW
temn.tti.queue.f2b.tap.output.queue=XML_T24
temn.tti.queue.f2b.tap.output.queue.bo=XML_T24_BO
temn.tti.queue.f2b.monitor.queue=MON
temn.tti.queue.f2b.error.queue=ERROR
temn.tti.queue.f2b.final.jms.queue.name=XML_B2F
temn.tti.queue.f2b.final.jms.queue.name.bo=XML_B2F_BO
temn.tti.queue.f2b.ofsml.request=ttiOFSMLQueue
temn.tti.queue.f2b.ofsml.reply=ttiOFSMLReplyQueue
spring.main.allow-circular-references = true
#Camel Route Exception Retry
message.retry=2
#Ofsml error in T24 retry
message.ofsml.fail.retry=2
#Ofsml timeout between retry-milliseconds
message.ofsml.fail.retry.timeout=20000
#Ofsml response timeout-milliseconds
message.ofsml.receive.timeout=30000
#Ofsml message time to live-milliseconds
message.ofsml.timetolive=50000
#ActiveMQ
concurrentConsumers=1
maxConcurrentConsumers=5
