#============B2F Queues===================
requestQueue=jms/queue/t24IFInboundQueue
b2f.input.queue=jms/queue/T24_JMS
b2f.single.input.queue=jms/queue/T24_IN
b2f.batch.input.queue=jms/queue/T24_BATCH_IN
b2f.output.queue=jms/queue/XML_B2F

#============F2B TAP INPUT NODE======
f2b.tap.input.queue=jms/queue/XML_F2B
f2b.tap.slow.queue=jms/queue/SLOW
f2b.tap.output.queue=jms/queue/XML_T24
f2b.monitor.queue =jms/queue/MON
f2b.error.queue =jms/queue/ERROR



#============Final f2b Output queue=======================
f2b.final.jms.queue.name=jms/queue/XML_B2F

#=================JMS User Name and connection factory details============
queue.server.username=XXXXXXX
queue.server.password=XXXXXXX
jms.initial.factory=org.jboss.naming.remote.client.InitialContextFactory
jms.provided.url=http-remoting://localhost:9089
jms.connection.factory=jms/RemoteConnectionFactory

#==================Adapter Config Design time======================
t24.adapter.service.username=XXXXXXX
t24.adapter.service.password=XXXXXXX
t24.adapter.service.url=http://localhost:8160/axis2/services/
t24.adapter.settings.file.path=C:/test/ofs.txt

#==================Adapter Config run time======================
t24.adadpter.server.host = localhost
t24.adadpter.server.port = 8160
t24.adadpter.server.user = XXXXXXX
t24.adadpter.server.password = XXXXXXX

#=======================
jms.correlationid.toread=123456789

#==================SSL Config======================
t24.adadpter.server.ssl.enable=false
t24.adadpter.server.ssl.trust.store.path=opt/mule/coelsa.jks
t24.adadpter.server.ssl.trust.store.pass=xxxxx
